//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente : Usuario
    {
        public Cliente()
        {
            this.Tarjetas = new HashSet<TarjetaCredito>();
            this.Puntos = new HashSet<PuntoCompra>();
            this.Compras = new HashSet<Compra>();
            this.PremioUsuarios = new HashSet<PremioXUsuario>();
        }
    
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string tipoDocumento { get; set; }
        public string numeroDocumento { get; set; }
        public string cuil { get; set; }
        public string mail { get; set; }
        public string telefono { get; set; }
        public string fechaNacimiento { get; set; }
        public string fechaCreacion { get; set; }
    
        public virtual ICollection<TarjetaCredito> Tarjetas { get; set; }
        public virtual ICollection<PuntoCompra> Puntos { get; set; }
        public virtual ICollection<Compra> Compras { get; set; }
        public virtual ICollection<PremioXUsuario> PremioUsuarios { get; set; }
    }
}
