//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int id { get; set; }
        public int publicacionId { get; set; }
        public System.DateTime fechaCompra { get; set; }
        public int tarjetaId { get; set; }
        public int clienteId { get; set; }
    
        public virtual Publicacion Publicacion { get; set; }
        public virtual TarjetaCredito TarjetaCredito { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual PuntoCompra PuntoCompra { get; set; }
    }
}
