//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domicilio
    {
        public int id { get; set; }
        public string calle { get; set; }
        public string numero { get; set; }
        public string codigoPostal { get; set; }
        public string departamento { get; set; }
        public string localidad { get; set; }
        public string ciudad { get; set; }
        public string piso { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
