//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public string empresa_Cuit { get; set; }
        public string empresa_mail { get; set; }
        public Nullable<decimal> empresa_telefono { get; set; }
        public string empresa_razon_social { get; set; }
        public Nullable<int> empresa_domicilio { get; set; }
        public Nullable<bool> empresa_estado { get; set; }
    }
}
