//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa_Domicilio
    {
        public int Id_Empresa { get; set; }
        public string Emp_Dom_Calle { get; set; }
        public Nullable<decimal> Emp_Nro_Calle { get; set; }
        public string Emp_Cod_Postal { get; set; }
        public string Emp_Depto { get; set; }
        public string Emp_Localidad { get; set; }
        public string Emp_Ciudad { get; set; }
        public Nullable<decimal> Emp_Piso { get; set; }
    }
}
