//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Empresa> Empresas { get; set; }
        public DbSet<Empresa_Domicilio> Empresa_Domicilio { get; set; }
        public DbSet<Funcionalidad> Funcionalidads { get; set; }
        public DbSet<FuncionalidadXRol> FuncionalidadXRols { get; set; }
        public DbSet<Rol> Rols { get; set; }
        public DbSet<RolXUsuario> RolXUsuarios { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
    }
}
