//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.ItemFacturas = new HashSet<ItemFactura>();
        }
    
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal total { get; set; }
        public decimal comision { get; set; }
        public int empresaId { get; set; }
    
        public virtual ICollection<ItemFactura> ItemFacturas { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
