//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grado
    {
        public Grado()
        {
            this.porcentaje = 0D;
        }
    
        public int id { get; set; }
        public string tipo { get; set; }
        public double porcentaje { get; set; }
    }
}
