//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemFactura
    {
        public int id { get; set; }
        public int facturaId { get; set; }
        public int compraId { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Compra Compra { get; set; }
    }
}
