//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacion
    {
        public Publicacion()
        {
            this.stock = 0;
            this.precio = 0D;
            this.Compras = new HashSet<Compra>();
        }
    
        public int id { get; set; }
        public int empresaId { get; set; }
        public int rubroId { get; set; }
        public int gradoId { get; set; }
        public string descripcion { get; set; }
        public int stock { get; set; }
        public System.DateTime fechaPublicacion { get; set; }
        public System.DateTime fechaEspectaculo { get; set; }
        public double precio { get; set; }
        public string direccion { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Rubro Rubro { get; set; }
        public virtual Grado GradoPublicacion { get; set; }
        public virtual ICollection<Compra> Compras { get; set; }
    }
}
