//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntoCompra
    {
        public PuntoCompra()
        {
            this.puntos = 0;
            this.puntosVigentes = 0;
        }
    
        public int id { get; set; }
        public int clienteId { get; set; }
        public int puntos { get; set; }
        public int puntosVigentes { get; set; }
        public System.DateTime fechaVencimiento { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Compra Compra { get; set; }
    }
}
