//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.activo = true;
            this.eliminado = false;
            this.RolXUsuarios = new HashSet<RolXUsuario>();
            this.FuncionalidadXRoles = new HashSet<FuncionalidadXRol>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
    
        public virtual ICollection<RolXUsuario> RolXUsuarios { get; set; }
        public virtual ICollection<FuncionalidadXRol> FuncionalidadXRoles { get; set; }
    }
}
