//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.FuncionalidadXRols = new HashSet<FuncionalidadXRol>();
            this.RolXUsuarios = new HashSet<RolXUsuario>();
        }
    
        public int Id_Rol { get; set; }
        public string nombre { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual ICollection<FuncionalidadXRol> FuncionalidadXRols { get; set; }
        public virtual ICollection<RolXUsuario> RolXUsuarios { get; set; }
    }
}
