//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.RolXUsuarios = new HashSet<RolXUsuario>();
        }
    
        public int Id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> cambioPsw { get; set; }
        public string creadoPor { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> intentos { get; set; }
        public Nullable<int> clienteId { get; set; }
        public string CuitEmpresa { get; set; }
        public Nullable<bool> Baja { get; set; }
        public Nullable<System.DateTime> Fecha_Password { get; set; }
    
        public virtual ICollection<RolXUsuario> RolXUsuarios { get; set; }
    }
}
