//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Usuario
    {
        public Usuario()
        {
            this.passwordAutogenerado = true;
            this.activo = true;
            this.intentos = 0;
            this.eliminado = false;
            this.RolXUsuarios = new HashSet<RolXUsuario>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public bool passwordAutogenerado { get; set; }
        public bool activo { get; set; }
        public Nullable<int> intentos { get; set; }
        public bool eliminado { get; set; }
    
        public virtual Domicilio Domicilio { get; set; }
        public virtual ICollection<RolXUsuario> RolXUsuarios { get; set; }
    }
}
